// (1) Let's delete all the boilerplate code generated by "create-react-app" and start writing our own components
import React from "react";
import ReactDOM from "react-dom";

import App from "./components/App";

// (3) At last, we render the main App component into the #root element
ReactDOM.render(<App />, document.querySelector("#root")) ;